lab:
  vars:
    ansible_python_interpreter: auto_silent
  hosts:
    192.168.253.130:22450

node_exporter:
  children:
    lab:

alertmanager:
  children:
    lab:

preprod:
  children:
    lab:

prod:
  children:
    lab:
